### ISSUE TITLE
0.62.2 -> 0.63.2 - Xcode error: Undefined symbol: _OBJC_CLASS_$_FlipperKitNetworkPlugin

### ISSUE THREAD

**Issue by BPetronel** [react-native-community/upgrade-support#98]
## Environment
System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 2.05 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.4.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.3 - /Users/username/Software/ruby/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found

## Upgrading version

0.62.2 -> 0.63.2

## Description

I recently upgraded from 0.61.5 to 0.62.2 and followed 
https://react-native-community.github.io/upgrade-helper/?from=0.61.5&to=0.62.2
and https://github.com/react-native-community/upgrade-support/issues/13
Having multiple targets inside Podfile I found that i have to add a custom configuration to Flipper pods as presented here: https://github.com/react-native-community/upgrade-support/issues/30#issuecomment-608495255

After that the whole build started to work flawless.

Now I wanted to upgrade to 0.63.2 and now the React native and Flipper pods were moved to '../node_modules/react-native/scripts/react_native_pods' without any possibility to specify: :configuration => ['Debug-dev', 'Release-dev']
and now i get the same error: 
`Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FlipperKitNetworkPlugin", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_SKIOSNetworkAdapter", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_FlipperKitReactPlugin", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_FKUserDefaultsPlugin", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_FlipperKitLayoutPlugin", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_SKDescriptorMapper", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_FlipperClient", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

## Reproducible demo
n/a

**Comment by rebekahshaw92** [comment]
I am facing the same problem and can't seem to find a fix

**Comment by BPetronel** [comment]
I simply just copy pasted what is inside '../node_modules/react-native/scripts/react_native_pods' in the podfile and changed the :configuration => ['Debug-dev', 'Release-dev'] for the debug pods and managed to make the build work again.
Keep in mind that any update to the react_native_pods might break you project, fixed package version might be a solution?

**Comment by rebekahshaw92** [comment]
I'm currently using react native 0.63.2

**Comment by tezqa** [comment]
The issue has been fixed in the latest version of the `react_native_pods.rb` file:
https://github.com/facebook/react-native/blob/master/scripts/react_native_pods.rb

But unfortunately not yet shipped with the latest version of React Native (0.63.2 at this time).

A temporary workaround is to overwrite the `use_flipper` method of `node_modules/react_native/scripts/react_native_pods.rb `by the new one.

**Comment by aprilmintacpineda** [comment]
I have tried upgrading to latest version of react, I still get the same error, I'm trying to build for multiple environments (local, staging, and prod) and I want to be able to install them all on the same device and be able to use them as if they are different apps, I'm following this guide on that http://blog.logicwind.com/adding-multiple-target/

but I got these errors
![image](https://user-images.githubusercontent.com/21032419/94754525-09557180-03c4-11eb-9837-24e1d9f20009.png)

Here's my Podfile

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

project 'embrace',
        'Debug' => :debug,
        'Release' => :release,
        'Local.Debug' => :debug,
        'Local.Release' => :release, 
        'Staging.Debug' => :debug,
        'Staging.Release' => :release

target 'embrace' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'embraceTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'embrace-tvOS' do
  # Pods for embrace-tvOS

  target 'embrace-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
```

**Comment by Anzormumladze** [comment]
any ideas how to fix ???

**Comment by aprilmintacpineda** [comment]
For me, I did not fix it, I just created a new react-native project with the same package name, copy-pasted my JS codes to that new one, and set-up all dependencies and 🎉 fixed.

**Comment by KristineTrona** [comment]
None of the above fixes worked for me. I have no idea if this is a good fix, but I changed the following in `AppDelegate.m` and it seems to have worked for me:

```
    #ifdef FB_SONARKIT_ENABLED
      InitializeFlipper(application);
    #endif
```

to 
```
  #if DEBUG
    #ifdef FB_SONARKIT_ENABLED
      InitializeFlipper(application);
    #endif
  #endif
```

**Comment by Luckygirlllll** [comment]
I have the same problem, is there any updates about this issue?

**Comment by Anzormumladze** [comment]
> I have the same problem, is there any updates about this issue?

Following the SOLUTIONS in the topic works for me, just one thing:

Enable Dead Code Stripping --> This needed to be done for the TARGETS level, not PROJECT level

**Comment by ismdcf** [comment]
Had the same issue. Was able to solve it, please check the reply for other similar issues I have explained it there 

https://github.com/react-native-community/upgrade-support/issues/30#issuecomment-723787804

**Comment by Dgdevesh** [comment]
> None of the above fixes worked for me. I have no idea if this is a good fix, but I changed the following in `AppDelegate.m` and it seems to have worked for me:
> 
> ```
>     #ifdef FB_SONARKIT_ENABLED
>       InitializeFlipper(application);
>     #endif
> ```
> 
> to
> 
> ```
>   #if DEBUG
>     #ifdef FB_SONARKIT_ENABLED
>       InitializeFlipper(application);
>     #endif
>   #endif
> ```

Thanks @KristineTrona this helped me alot

**Comment by dinukasal** [comment]
If you have following code in your Podfile comment it out,
`
  #   Enable Flipper for simulators only
   if target.name.start_with?('Flipper')
     target.build_configurations.each do |config|
       config.build_settings['VALID_ARCHS'] = 'arm64 arm64e'
       config.build_settings['ARCHS'] = '${ARCHS_STANDARD_64_BIT}'
     end
   end
`

**Comment by dinukasal** [comment]
It worked for me when I commented out following code in my Podfile,
```
  #   Enable Flipper for simulators only
   if target.name.start_with?('Flipper')
     target.build_configurations.each do |config|
       config.build_settings['VALID_ARCHS'] = 'arm64 arm64e'
       config.build_settings['ARCHS'] = '${ARCHS_STANDARD_64_BIT}'
     end
   end
```
